<?php
/**
 * @file
 * Code for the Off Categories Feature feature.
 */

include_once 'off_categories_feature.features.inc';

/**
 * Implements hook_block_view_MODULE_DELTA_alter();
 */
function off_categories_feature_block_view_collabco_groups_feature_group_toolbar_alter(&$data, $block) {

  // Block is empty for some reason. Dont try to change that.
  if (empty($data['content']['add-content-list'])) { 
    return;
  }
  $og_context = og_context();
  if (empty($og_context)) {
    return;
  }
  
  $gid = $og_context['gid'];
  $bundle = 'categories';
  $group_type = 'node';

  // Dont need this without og permissions...
  //$group = entity_load($group_type, array($gid));
  
  $vocabulary = taxonomy_vocabulary_machine_name_load($bundle);

  // Construct permission name string for the taxonomy bundle. Og dosent provide
  // term permissions by default so any user can add terms, just not save to a
  // group, and they wont see this message if they arent in the group. So its
  // sufficient for now but still a hack job.
  $string = "edit terms in " .  $vocabulary->vid;
  
  //It should look like this...
  //$string = $group_type .  $group[$gid]->type . ':' . "edit terms in " .  $vocabulary->vid;
  
  // Add a menu link if the current user can create taxonomy terms in the bundle.
  if (user_access($string)) {
    $items = array();
    $options = collabco_groups_feature_prepopulate_query($gid);
    $text = t('Create ') . $vocabulary->name;
    $url = "node/$gid/taxonomy/$bundle/add/";
    $data['content']['add-content-list']['#items']['term_categories'] = l($text, $url, $options); 
    // Link to view to edit all terms in vocab and group.
    $text = t('View ') . $vocabulary->name . ' ' . t('terms');
    $url = "node/$gid/taxonomy/$bundle/";
    $data['content']['add-content-list']['#items']["view_term_$bundle"] = l($text, $url); 
  }
}

